### ISSUE TITLE
support for custom ssh_config and path to ssh_priv_key

### ISSUE THREAD

**Issue by patrikh-dev** [DataKnox/nornir_pyez#14]
hi @DataKnox 
I tried to open pull request but I got permission denied, probably don't have permission to create a new branch.

PYEZ supports optional parameters for path to `ssh_key` and `ssh_config`, i tested it here: https://github.com/patrikh-dev/pyez_test

Below is update which should add support for these optional parameters also in `nornir_pyez`.  

pls have a look and if possible add it to your package, thanks

```bash
--- a/nornir_pyez/plugins/connections/__init__.py
+++ b/nornir_pyez/plugins/connections/__init__.py
@@ -27,6 +27,8 @@ class Pyez:
             "password": password,
             "port": port,
             "optional_args": {},
+            "ssh_config": extras["ssh_config"] if "ssh_config" in extras.keys() else None,
+            "ssh_private_key_file": extras["ssh_private_key_file"] if "ssh_private_key_file" in extras.keys() else None,
         }
```

## Custom SSH config file or path to ssh key

* definition inside `hosts.yaml`

```yaml
hostname:
    ...
    connection_options:
        pyez:
            extras:
                ssh_config: "path_to_ssh_config"
                ssh_private_key_file: "path_to_ssh_key"
```

* definition inside `groups.yaml`

```yaml
group_name:
    ...
    connection_options:
        pyez:
            extras:
                ssh_config: "path_to_ssh_config"
                ssh_private_key_file: "path_to_ssh_key"
```

* definition inside code
  * requires to have definition of connection_options/pyez/extras under host or group (depends which definition is used inside the code) otherwise `KeyError: 'pyez'` is generated

```yaml
host / group:
    connection_options:
        pyez:
            extras: {}
```

```python
# per host definition
nr.inventory.hosts['hostname'].connection_options['pyez'].extras['ssh_config'] = "path_to_ssh_config"
nr.inventory.hosts['hostname'].connection_options['pyez'].extras['ssh_private_key_file'] = "path_to_ssh_key"
# per group definition
nr.inventory.groups['group_name'].connection_options['pyez'].extras['ssh_config'] = "path_to_ssh_config"
nr.inventory.groups['group_name'].connection_options['pyez'].extras['ssh_private_key_file'] = "path_to_ssh_key"
```
